"""
============================================================
Agentic World — Fine-Tuning Job (Per-Cluster QLoRA)
============================================================
Fine-tunes separate LoRA adapters for each behavioral cluster
using QLoRA (PEFT + BitsAndBytes).

Reads per-cluster training data from data/training/cluster_<id>_train.jsonl
generated by build_training_data.py.

Usage:
    # Train all clusters (loads model once, trains 5 adapters sequentially)
    python finetune_job.py --all-clusters

    # Train a single cluster
    python finetune_job.py --cluster 0

    # Override hyperparams
    python finetune_job.py --all-clusters --epochs 3 --lora-rank 32 --no-wandb
============================================================
"""

import os
import json
import sys
import gc
import argparse
import torch
import wandb
from pathlib import Path
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig
from datasets import load_dataset, Dataset as HFDataset

sys.path.insert(0, str(Path(__file__).parent))
from config import TRAINING_DIR, MODELS_DIR, CLUSTERS_DIR, TARGET_APP_NAME, ensure_data_dirs

# ============================================================
# PARSE ARGS
# ============================================================

parser = argparse.ArgumentParser(description="Fine-tune per-cluster LoRA adapters with QLoRA")
parser.add_argument("--all-clusters", action="store_true", help="Train all clusters sequentially")
parser.add_argument("--cluster", type=int, default=None, help="Train a single cluster by ID")
parser.add_argument("--model", type=str, default="mistralai/Mistral-7B-Instruct-v0.3")
parser.add_argument("--epochs", type=int, default=5)
parser.add_argument("--batch-size", type=int, default=1)
parser.add_argument("--gradient-accumulation", type=int, default=8)
parser.add_argument("--learning-rate", type=float, default=2e-4)
parser.add_argument("--lora-rank", type=int, default=16)
parser.add_argument("--lora-alpha", type=int, default=32)
parser.add_argument("--max-seq-length", type=int, default=2048)
parser.add_argument("--no-wandb", action="store_true", help="Disable W&B tracking")
parser.add_argument("--skip-inference", action="store_true", help="Skip inference test after training")
cli_args = parser.parse_args()

if not cli_args.all_clusters and cli_args.cluster is None:
    print("ERROR: Specify --all-clusters or --cluster <id>")
    sys.exit(1)

ensure_data_dirs()

os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

USE_WANDB = not cli_args.no_wandb


# ============================================================
# DETERMINE WHICH CLUSTERS TO TRAIN
# ============================================================

def get_cluster_ids() -> list[int]:
    """Discover which clusters have training data."""
    if cli_args.cluster is not None:
        return [cli_args.cluster]

    # Find all cluster_*_train.jsonl files
    train_files = sorted(TRAINING_DIR.glob("cluster_*_train.jsonl"))
    ids = []
    for f in train_files:
        # cluster_0_train.jsonl -> 0
        try:
            cid = int(f.stem.split("_")[1])
            ids.append(cid)
        except (IndexError, ValueError):
            continue
    return ids


def load_cluster_meta(cluster_id: int) -> dict:
    """Load cluster metadata from clusters.json if available."""
    cluster_path = CLUSTERS_DIR / "clusters.json"
    if cluster_path.exists():
        with open(cluster_path) as f:
            data = json.load(f)
        for c in data.get("clusters", []):
            if c["id"] == cluster_id:
                return c
    return {"id": cluster_id, "label": f"Cluster {cluster_id}"}


# ============================================================
# LOAD BASE MODEL (once, shared across all cluster trainings)
# ============================================================

print("=" * 60)
print("AGENTIC WORLD — PER-CLUSTER FINE-TUNING")
print("=" * 60)

cluster_ids = get_cluster_ids()
print(f"Model:    {cli_args.model}")
print(f"Clusters: {cluster_ids}")
print(f"LoRA:     rank={cli_args.lora_rank}, alpha={cli_args.lora_alpha}")
print(f"Epochs:   {cli_args.epochs}, LR: {cli_args.learning_rate}")
print("=" * 60)

print(f"\nLoading base model: {cli_args.model}")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    bnb_4bit_use_double_quant=True,
)

try:
    import flash_attn  # noqa: F401
    attn_impl = "flash_attention_2"
    print("  Using Flash Attention 2")
except ImportError:
    attn_impl = "sdpa"
    print("  Using SDPA")

tokenizer = AutoTokenizer.from_pretrained(cli_args.model, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"


def to_text(messages):
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)


# ============================================================
# TRAIN ONE CLUSTER
# ============================================================

def train_cluster(cluster_id: int) -> dict:
    """Train a LoRA adapter for one cluster. Returns results dict."""

    train_file = str(TRAINING_DIR / f"cluster_{cluster_id}_train.jsonl")
    val_file = str(TRAINING_DIR / f"cluster_{cluster_id}_val.jsonl")
    output_dir = str(MODELS_DIR / f"cluster_{cluster_id}_lora")

    if not Path(train_file).exists():
        print(f"  SKIP: {train_file} not found")
        return {"cluster_id": cluster_id, "status": "skipped"}

    if not Path(val_file).exists():
        print(f"  SKIP: {val_file} not found")
        return {"cluster_id": cluster_id, "status": "skipped"}

    meta = load_cluster_meta(cluster_id)
    label = meta.get("label", f"Cluster {cluster_id}")

    print(f"\n{'='*60}")
    print(f"TRAINING CLUSTER {cluster_id}: {label}")
    print(f"{'='*60}")
    print(f"  Train: {train_file}")
    print(f"  Val:   {val_file}")
    print(f"  Output: {output_dir}")

    # W&B
    run = None
    if USE_WANDB:
        run = wandb.init(
            project=os.environ.get("WANDB_PROJECT", "agentic-world"),
            job_type="finetune",
            name=f"cluster_{cluster_id}_{label.replace(' ', '_')}",
            config={
                "cluster_id": cluster_id,
                "cluster_label": label,
                "model": cli_args.model,
                "lora_rank": cli_args.lora_rank,
                "lora_alpha": cli_args.lora_alpha,
                "epochs": cli_args.epochs,
                "learning_rate": cli_args.learning_rate,
            },
            reinit=True,
        )

    # Load fresh base model for each cluster
    print(f"  Loading base model...")
    base_model = AutoModelForCausalLM.from_pretrained(
        cli_args.model,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
        attn_implementation=attn_impl,
        trust_remote_code=True,
    )
    base_model = prepare_model_for_kbit_training(base_model, use_gradient_checkpointing=True)

    lora_config = LoraConfig(
        r=cli_args.lora_rank,
        lora_alpha=cli_args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(base_model, lora_config)
    model.print_trainable_parameters()

    # Load dataset
    dataset = load_dataset("json", data_files={"train": train_file, "eval": val_file})
    print(f"  Train: {len(dataset['train'])} examples, Val: {len(dataset['eval'])} examples")

    train_texts = [to_text(ex["messages"]) for ex in dataset["train"]]
    eval_texts = [to_text(ex["messages"]) for ex in dataset["eval"]]

    train_dataset = HFDataset.from_dict({"text": train_texts})
    eval_dataset = HFDataset.from_dict({"text": eval_texts})

    # Train
    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        args=SFTConfig(
            output_dir=output_dir,
            per_device_train_batch_size=cli_args.batch_size,
            gradient_accumulation_steps=cli_args.gradient_accumulation,
            num_train_epochs=cli_args.epochs,
            learning_rate=cli_args.learning_rate,
            warmup_steps=10,
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            seed=42,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=1,
            eval_strategy="epoch",
            eval_accumulation_steps=1,
            save_strategy="epoch",
            save_total_limit=1,
            load_best_model_at_end=False,
            report_to="wandb" if USE_WANDB else "none",
            run_name=f"cluster_{cluster_id}" if USE_WANDB else None,
            max_length=cli_args.max_seq_length,
            dataset_text_field="text",
            packing=False,
            dataset_num_proc=1,
            dataloader_num_workers=0,
            gradient_checkpointing=True,
            gradient_checkpointing_kwargs={"use_reentrant": False},
            optim="adamw_8bit",
        ),
    )

    gpu_stats = torch.cuda.get_device_properties(0)
    print(f"  GPU: {gpu_stats.name} ({gpu_stats.total_memory / 1024**3:.1f} GB)")

    train_result = trainer.train()
    peak_memory = torch.cuda.max_memory_reserved() / 1024**3

    # Evaluate
    eval_results = trainer.evaluate()

    print(f"  Train loss: {train_result.training_loss:.4f}")
    print(f"  Eval loss:  {eval_results['eval_loss']:.4f}")
    print(f"  Time:       {train_result.metrics['train_runtime']:.1f}s")
    print(f"  Peak VRAM:  {peak_memory:.1f} GB")

    # Save adapter
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)

    config_path = os.path.join(output_dir, "training_config.json")
    with open(config_path, "w") as f:
        json.dump({
            "cluster_id": cluster_id,
            "cluster_label": label,
            "base_model": cli_args.model,
            "lora_rank": cli_args.lora_rank,
            "lora_alpha": cli_args.lora_alpha,
            "epochs": cli_args.epochs,
            "learning_rate": cli_args.learning_rate,
            "max_seq_length": cli_args.max_seq_length,
            "train_examples": len(train_dataset),
            "eval_examples": len(eval_dataset),
            "final_train_loss": train_result.training_loss,
            "final_eval_loss": eval_results["eval_loss"],
            "training_time_s": train_result.metrics["train_runtime"],
            "peak_vram_gb": peak_memory,
        }, f, indent=2)

    print(f"  Adapter saved to {output_dir}")

    if USE_WANDB and run:
        wandb.log({
            "final_train_loss": train_result.training_loss,
            "final_eval_loss": eval_results["eval_loss"],
            "training_time_s": train_result.metrics["train_runtime"],
            "peak_vram_gb": peak_memory,
        })
        adapter_artifact = wandb.Artifact(
            name=f"cluster-{cluster_id}-lora",
            type="model",
            metadata={"cluster_id": cluster_id, "cluster_label": label},
        )
        adapter_artifact.add_dir(output_dir)
        run.log_artifact(adapter_artifact)
        wandb.finish()

    result = {
        "cluster_id": cluster_id,
        "label": label,
        "status": "completed",
        "train_loss": train_result.training_loss,
        "eval_loss": eval_results["eval_loss"],
        "train_examples": len(train_dataset),
        "time_s": train_result.metrics["train_runtime"],
        "adapter_path": output_dir,
    }

    # Cleanup GPU memory before next cluster
    del model, base_model, trainer, train_dataset, eval_dataset
    gc.collect()
    torch.cuda.empty_cache()

    return result


# ============================================================
# MAIN: Train all requested clusters
# ============================================================

results = []
for cid in cluster_ids:
    result = train_cluster(cid)
    results.append(result)

# Summary
print(f"\n{'='*60}")
print("ALL TRAINING COMPLETE")
print("=" * 60)
for r in results:
    if r["status"] == "skipped":
        print(f"  Cluster {r['cluster_id']}: SKIPPED")
    else:
        print(f"  Cluster {r['cluster_id']} ({r['label']}): "
              f"train_loss={r['train_loss']:.4f}, eval_loss={r['eval_loss']:.4f}, "
              f"{r['train_examples']} examples, {r['time_s']:.0f}s")
        print(f"    Adapter: {r['adapter_path']}")

# Save summary
summary_path = MODELS_DIR / "training_summary.json"
with open(summary_path, "w") as f:
    json.dump(results, f, indent=2)
print(f"\nSummary saved to {summary_path}")
print(f"\nNext step: python agentic_loop.py --url <sandbox_url> --app-description \"...\"")
print("=" * 60)
